// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR4weCsadri2RgR7abeJQowkmUd2GM7NU',
    appId: '1:333201858414:web:3ccb37c630ba04ad23ab7f',
    messagingSenderId: '333201858414',
    projectId: 'final-year-project-du0585',
    authDomain: 'final-year-project-du0585.firebaseapp.com',
    databaseURL: 'https://final-year-project-du0585-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-du0585.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJ_x8BLAw9tvKNBTLENAWwq-DxTvpvS0',
    appId: '1:333201858414:android:189431e050f8254c23ab7f',
    messagingSenderId: '333201858414',
    projectId: 'final-year-project-du0585',
    databaseURL: 'https://final-year-project-du0585-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-du0585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgKs0iG2SlJBPDIKrdRo3SkyMu8STUI4',
    appId: '1:333201858414:ios:992b0d82cd671e9023ab7f',
    messagingSenderId: '333201858414',
    projectId: 'final-year-project-du0585',
    databaseURL: 'https://final-year-project-du0585-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-du0585.firebasestorage.app',
    iosBundleId: 'com.example.mobileSimpliPlan',
  );
}
